#!/usr/bin/env python3
"""
proxy.py — WatsonX Dashboard local dev server

Serves the dashboard on http://localhost:8080 AND acts as a CORS-safe
proxy for IBM Cloud IAM + watsonx.ai API calls.

Usage:
    export WATSONX_API_KEY=your_api_key
    export WATSONX_PROJECT_ID=your_project_id
    export WATSONX_MODEL_ID=ibm/granite-3-8b-instruct   # optional
    export WATSONX_URL=https://us-south.ml.cloud.ibm.com # optional
    python3 proxy.py

Then open: http://localhost:8080/pages/index.html
"""

import http.server
import json
import os
import urllib.request
import urllib.parse
import urllib.error
from pathlib import Path

# ── Config from environment ───────────────────────────────────────────────────

API_KEY    = os.environ.get("WATSONX_API_KEY", "")
PROJECT_ID = os.environ.get("WATSONX_PROJECT_ID", "")
MODEL_ID   = os.environ.get("WATSONX_MODEL_ID", "ibm/granite-3-8b-instruct")
WX_URL     = os.environ.get("WATSONX_URL", "https://us-south.ml.cloud.ibm.com")
PORT       = int(os.environ.get("PORT", 8080))

# Warn early if credentials are missing
if not API_KEY or not PROJECT_ID:
    print("⚠️  WARNING: WATSONX_API_KEY or WATSONX_PROJECT_ID not set in environment.")
    print("   The chatbot will fail to authenticate. Export them before starting.\n")

# ── Generated config.js content (injected at runtime) ────────────────────────

CONFIG_JS = f"""/* Auto-generated by proxy.py from environment variables — do not edit */
var WATSONX_CONFIG = {{
  PROJECT_ID: "{PROJECT_ID}",
  MODEL_ID:   "{MODEL_ID}",
  URL:        "{WX_URL}",
  PROXY:      true
}};
"""

# ── CORS headers added to every response ─────────────────────────────────────

CORS_HEADERS = {
    "Access-Control-Allow-Origin":  "*",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
}

# ── Request handler ───────────────────────────────────────────────────────────

class ProxyHandler(http.server.SimpleHTTPRequestHandler):

    def log_message(self, fmt, *args):
        print(f"  {self.address_string()} — {fmt % args}")

    # ------------------------------------------------------------------
    # Preflight (OPTIONS) for every path
    # ------------------------------------------------------------------
    def do_OPTIONS(self):
        self.send_response(204)
        for k, v in CORS_HEADERS.items():
            self.send_header(k, v)
        self.end_headers()

    # ------------------------------------------------------------------
    # GET — intercept /assets/js/config.js and serve it from env vars
    # ------------------------------------------------------------------
    def _base_path(self):
        """Return path without query string."""
        return self.path.split("?")[0]

    def do_GET(self):
        if self._base_path() == "/assets/js/config.js":
            self._serve_config_js()
            return
        # Everything else: serve static files from the project root
        super().do_GET()

    # ------------------------------------------------------------------
    # POST — proxy /proxy/iam-token and /proxy/watsonx
    # ------------------------------------------------------------------
    def do_POST(self):
        path = self._base_path()
        if path == "/proxy/iam-token":
            self._proxy_iam_token()
        elif path == "/proxy/watsonx":
            self._proxy_watsonx()
        else:
            self.send_error(404, "Not found")

    # ------------------------------------------------------------------
    # Serve dynamically generated config.js
    # ------------------------------------------------------------------
    def _serve_config_js(self):
        body = CONFIG_JS.encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/javascript; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        for k, v in CORS_HEADERS.items():
            self.send_header(k, v)
        self.end_headers()
        self.wfile.write(body)

    # ------------------------------------------------------------------
    # Proxy: POST /proxy/iam-token  →  IBM IAM
    # ------------------------------------------------------------------
    def _proxy_iam_token(self):
        iam_url = "https://iam.cloud.ibm.com/identity/token"
        body = urllib.parse.urlencode({
            "grant_type": "urn:ibm:params:oauth:grant-type:apikey",
            "apikey": API_KEY,
        }).encode("utf-8")

        req = urllib.request.Request(
            iam_url,
            data=body,
            headers={"Content-Type": "application/x-www-form-urlencoded"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req) as resp:
                data = resp.read()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                for k, v in CORS_HEADERS.items():
                    self.send_header(k, v)
                self.end_headers()
                self.wfile.write(data)
        except urllib.error.HTTPError as e:
            err = e.read()
            self.send_response(e.code)
            self.send_header("Content-Type", "application/json")
            for k, v in CORS_HEADERS.items():
                self.send_header(k, v)
            self.end_headers()
            self.wfile.write(err)
        except urllib.error.URLError as e:
            body = json.dumps({"error": f"Network error contacting IAM: {e.reason}"}).encode("utf-8")
            self.send_response(502)
            self.send_header("Content-Type", "application/json")
            for k, v in CORS_HEADERS.items():
                self.send_header(k, v)
            self.end_headers()
            self.wfile.write(body)

    # ------------------------------------------------------------------
    # Proxy: POST /proxy/watsonx  →  watsonx.ai chat endpoint (streaming)
    # ------------------------------------------------------------------
    def _proxy_watsonx(self):
        content_length = int(self.headers.get("Content-Length", 0))
        raw_body = self.rfile.read(content_length)

        wx_endpoint = f"{WX_URL}/ml/v1/text/chat?version=2024-05-01"

        # Read the Authorization header forwarded from the browser
        auth = self.headers.get("Authorization", "")

        req = urllib.request.Request(
            wx_endpoint,
            data=raw_body,
            headers={
                "Content-Type": "application/json",
                "Authorization": auth,
            },
            method="POST",
        )

        try:
            with urllib.request.urlopen(req) as resp:
                # Stream the response back chunk by chunk
                self.send_response(200)
                self.send_header("Content-Type", resp.headers.get("Content-Type", "application/json"))
                self.send_header("Transfer-Encoding", "chunked")
                for k, v in CORS_HEADERS.items():
                    self.send_header(k, v)
                self.end_headers()

                while True:
                    chunk = resp.read(4096)
                    if not chunk:
                        break
                    # Write HTTP chunked encoding
                    self.wfile.write(f"{len(chunk):X}\r\n".encode())
                    self.wfile.write(chunk)
                    self.wfile.write(b"\r\n")
                    self.wfile.flush()
                # Final empty chunk
                self.wfile.write(b"0\r\n\r\n")
                self.wfile.flush()

        except urllib.error.HTTPError as e:
            err = e.read()
            self.send_response(e.code)
            self.send_header("Content-Type", "application/json")
            for k, v in CORS_HEADERS.items():
                self.send_header(k, v)
            self.end_headers()
            self.wfile.write(err)
        except urllib.error.URLError as e:
            body = json.dumps({"error": f"Network error contacting watsonx: {e.reason}"}).encode("utf-8")
            self.send_response(502)
            self.send_header("Content-Type", "application/json")
            for k, v in CORS_HEADERS.items():
                self.send_header(k, v)
            self.end_headers()
            self.wfile.write(body)

# ── Start server ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    os.chdir(Path(__file__).parent)  # serve from project root
    server = http.server.HTTPServer(("", PORT), ProxyHandler)
    print(f"✅  Dashboard:  http://localhost:{PORT}/pages/index.html")
    print(f"   IAM proxy:  http://localhost:{PORT}/proxy/iam-token")
    print(f"   WX  proxy:  http://localhost:{PORT}/proxy/watsonx")
    print(f"   Config JS:  http://localhost:{PORT}/assets/js/config.js  (from env)\n")
    print("   Press Ctrl+C to stop.\n")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nServer stopped.")
